### ISSUE TITLE
Add slope of main road according to the level measurements on the plan

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#10]
The slope of the main road needs to be smoothed out (just like the side road). Levels are indicated on the most recent version of the plan with levels that I sent you.

![slide1](https://cloud.githubusercontent.com/assets/4740995/10123180/548e376a-64f8-11e5-87e7-cca683a785dd.JPG)

**Comment by ghost** [comment]
Fix this issue

**Comment by atomrab** [comment]
If the measurements are correct, we can close this. It seems a little high outside room 28 and a little low outside the chapel, but this may just be my visual impression.

**Comment by ghost** [comment]
I had a look at this issue. And I change a bit the level. But you need to see if it's OK. The problem is that we have only couple of GIS points outside.

**Comment by atomrab** [comment]
This looks better to me. I think it works, even if we don't have the points, so let's go with it.
