### ISSUE TITLE
The chapel should be completed

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#11]
The chapel needs a roof (two inclined planes to create a pitched roof) and its floor needs to be raised to the level indicated on the plan. It would also be interesting to try to add the two tombs (basically 3d rectangular voids about 1.5 meters deep). The red indicates the level of the road, the green the approximate level of the floor.

It's not marked here, but there should also be a transition between the road level and the step up into the courtyard, which should not be that high (so the transition is probably a slope).

![slide2](https://cloud.githubusercontent.com/assets/4740995/10123184/956ec2a4-64f8-11e5-9614-a4dace38b506.JPG)

**Comment by atomrab** [comment]
There's still a little work to do on the chapel. The door needs a lintel, as below: 

![slide1](https://cloud.githubusercontent.com/assets/4740995/11453908/703eabf0-95e2-11e5-9401-c9ceae0f0834.JPG)

and there's a gap between the courtyard surface and the apse, here:

![slide4](https://cloud.githubusercontent.com/assets/4740995/11453920/94ec79c8-95e2-11e5-8f8f-67007d4f4565.JPG)

I can't tell if you've moved the floor up to the correct level, but it's worth checking that too.

**Comment by ghost** [comment]
Fixed this issue. Added a lintel and corrected a floor level.

**Comment by atomrab** [comment]
These issues all look closed. The roof will at some point need to be changed from a triangular solid to two inclined planes (that is, there should not be a flat interior ceiling -- like the inside of a church, the area should be open inside all the way up to the roof). And the apse will need to have a separate cylindrical wall and half-dome tiled roof. But we can open new issues for these down the road.
