### ISSUE TITLE
Smooth out the join between the wall and upper wall/roof of the back part of room 30

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#12]
There's a visible offset between the upper part of the wall and roof of the back of room 30, and the lower part of the wall. This should be a smooth surface.

![slide3](https://cloud.githubusercontent.com/assets/4740995/10123194/01f23942-64f9-11e5-82a0-34117b4413d4.JPG)

**Comment by ghost** [comment]
Fix this issue. Now it's smooth as it should be
