### ISSUE TITLE
Floor level in room 35 should be irregular -- higher on street side, lower inside complex

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#13]
I think I marked different levels for the floor of room 35 on the plan with the levels -- the floor is higher on the street side, making a sort of shelf, and lower toward the interior of the block. Originally there seem to have been a couple of pithoi on that shelf. The red line here indicates the approximate profile of the floor.

![slide4](https://cloud.githubusercontent.com/assets/4740995/10123209/534a41f4-64f9-11e5-987c-babffca44d1a.JPG)

**Comment by ghost** [comment]
Fix this issue. I change the floor level to the profile you have provided.
