### ISSUE TITLE
Insert pit in small court under projecting upper floor of room 38

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#14]
This is the sewage pit we've been discussing. I think it's on the plan. We should put it in; it was about 1 meter deep, below the excavated floor surface.

![slide5](https://cloud.githubusercontent.com/assets/4740995/10123215/8966b024-64f9-11e5-83f7-a6d62b4a1028.JPG)

**Comment by ghost** [comment]
Fix this issue
