### ISSUE TITLE
Make household pit inside room 38 oval, and deeper

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#15]
This pit was an irregular flattened oval, with its long axis parallel to the wall. It was 1 to 1.5 meters deep, too. It should also be on one of the plans you have, for accurate dimensions.

![slide6](https://cloud.githubusercontent.com/assets/4740995/10123224/b6a0a20c-64f9-11e5-9a72-f8aeb069120b.JPG)

**Comment by ghost** [comment]
Fix this issue.
