### ISSUE TITLE
Add higher terrace wall along the full length of courtyard 31, stretching back from room 30

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#16]
You already have a higher ground level near the wall of room 30, from the courtyard, but this should stretch all the way back to the edge of the model at a somewhat higher level (probably just below the lowest part of the roofline of room 30, on the corridor side). In the first phase, this was just a terrace wall; in the second phase, room 31a will be built against it.

![slide7](https://cloud.githubusercontent.com/assets/4740995/10123262/fdd44e5c-64fa-11e5-9fc3-6c3c3edf7ed3.JPG)

**Comment by ghost** [comment]
Fix this issue
