### ISSUE TITLE
Problem with surface of courtyard 31 in area between room 30 and room 38

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#19]
The piece of ground in the small alley between these two rooms, under the stairs to the second floor of complex 2, has tilted for some reason, and should be brought back to level.

![slide2](https://cloud.githubusercontent.com/assets/4740995/11453935/e98ca7d2-95e2-11e5-912c-a23e814b34b0.JPG)

**Comment by ghost** [comment]
Fixed this bug

**Comment by atomrab** [comment]
Fixed, but now the passage between the stairs and room 30 is too narrow to get by without jumping. Can we lower the projecting block on the stairs a little? Good to know how tight that is.

**Comment by ghost** [comment]
I made it lower

**Comment by atomrab** [comment]
Easy to pass now. Thanks!
