### ISSUE TITLE
Add sill and lower lintel on door from room 38 to courtyard 31

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#2]
The lintel should be well below the level of the floor above, and the transition from room to courtyard should include a masonry sill (rectangular solid).

![slide2](https://cloud.githubusercontent.com/assets/4740995/9562040/2a76cfca-4e26-11e5-9400-4fadf19b76da.JPG)

**Comment by ghost** [comment]
Fix the issue
