### ISSUE TITLE
Surface of the main courtyard should be basically level

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#20]
The surface of the main courtyard -- at least when you look at it against the wall of the chapel -- seems to be rising to the center and then sloping down again, but should be roughly level according to the Z-coordinates we have for it, which should be respected -- it's ok if it tilts down to one side or the other, but it shouldn't rise in the center.

![slide5](https://cloud.githubusercontent.com/assets/4740995/11453952/827d8b5a-95e3-11e5-9bd7-a353da3a4dfc.JPG)

**Comment by ghost** [comment]
Fixed this issue
