### ISSUE TITLE
Walls along the N and NE side of the courtyard need to be raised

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#21]
Given the concern for security shown by the locking door that closes off room 30 and the area around it, it seems to me that the walls dividing this area from the courtyard should be raised (right now, a visitor could simply hop over and down into the area of room 30). If that wall is raised, the other walls between the courtyard and complex 3 should also be raised, as -- probably -- should the roof of room 29. Let's try raising the wall between complex 2 and the main court 1 to 1.5 meters, and adjusting the room of room 29 accordingly; with that done, let's see what happens to the wall separating complex 3 from the main courtyard. I think that should be raised anyway, since the door between the main court and room 32 has always seemed a little low. Adjustments will probably also need to be made to the wall between room 28 and the chapel, and between room 28 and the street.

![slide3](https://cloud.githubusercontent.com/assets/4740995/11454002/15dcac5e-95e5-11e5-8572-d1cfb26bfad9.JPG)

**Comment by ghost** [comment]
I lifted the walls and Room 30 for about a 1 meter. But I didn't touch Room 29.

**Comment by atomrab** [comment]
I realize, looking that this, that it makes sense to raise the wall between room 29 and the courtyard to the level of the wall between the courtyard and complex 2 -- I think it would have made more sense for the builders to build the roof of 29 up against a higher wall than to leave the relatively fragile mud-mortared wall open at the end. If we raise that wall as high as the upper side of the roof of 29, we may need to raise the wall of complex 2 the same amount.

![rm29_edits](https://cloud.githubusercontent.com/assets/4740995/12374709/cccfb6f4-bc69-11e5-9d3c-ac2f4008a7b4.jpg)

Once that's done, I think this looks good. How hard will it be to raise or lower these solids when everything is textured? There are some very interesting effects on visibility, and it might be a good way to try a few different hypotheses.

**Comment by ghost** [comment]
![screenshot from 2016-02-06 15 56 29](https://cloud.githubusercontent.com/assets/5684720/12867628/92579e9c-ccea-11e5-8fb4-ddfcb9ba846b.png)
You are right. It makes more sense now. I've made a change as you've suggested. But I need you to have a look if it's ok for you.

**Comment by atomrab** [comment]
That's not exactly what I meant -- rather than raising the roof of 29, which I think makes it too high, I meant just raising the courtyard wall, but keeping the roof in the same place, butted up against it as in the picture below:

![image0007](https://cloud.githubusercontent.com/assets/4740995/12868930/98a63686-ccd7-11e5-90d7-a58fb0bb32a8.JPG)

**Comment by atomrab** [comment]
Also, room 30 looks too high now, especially from the back. Can we change the pitch of the room to about 10% and lower the rear side? We can even butt the roof up against the courtyard wall, as I suggest with 29. There's no evidence of a second floor, and there's no reason that they would have built that room up so high if they weren't going to have a second floor.

**Comment by ghost** [comment]
I made a changes for the room 29 as you have suggested. And I did lower down room 30 and I made a pitch to about 10 percent lower. But I need if you have a look especially about room 30.

**Comment by ghost** [comment]
And I made a far part of courtyard walls at the same level as others

**Comment by atomrab** [comment]
Room 29 and the courtyard walls look great. I think that room 30 still needs to be lowered by about a meter. The roof can abut the courtyard wall just like the roof of room 29. It just doesn't make sense that it would be this tall without a second floor. It may help to raise the height of the doorways by about 30cm as well.

**Comment by ghost** [comment]
I did the change to the room 30 as you have suggested.

**Comment by atomrab** [comment]
This looks good. I think it makes a lot more sense in terms of height. The upper corner of the roof next to the courtyard is still a little weird, but I think we can stop tweaking.
