### ISSUE TITLE
Doors and shutters

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#22]
We'll want to add wooden doors for most of the door openings (ideally, doors that can be opened with a tap or by coming close to them), and shutters for the windows (I will talk to Kostis about whether these should open inward or outward). When we're ready to do this, let me know and I'll sketch out a plan with the position of doors and the direction they should open.

**Comment by ghost** [comment]
What do you think about this door. Can I use it as a style reference? Or feel free to add your image here.
![greek-door](https://cloud.githubusercontent.com/assets/5684720/12868015/753b1a14-ccf4-11e5-89b7-3fbc00200460.jpg)
I'm going to start making doors and a shutters for the windows now. When you get the sketch, please just send it to me, or attach sketch to this open issue.

This I found for the windows. Please let me know which you like, or add your images, please.
![old-building-shutter-wood-retro-style](https://cloud.githubusercontent.com/assets/5684720/12868034/6d8589de-ccf5-11e5-8823-595ec521978e.jpg)

![old_greek_window_187154](https://cloud.githubusercontent.com/assets/5684720/12868035/76edba64-ccf5-11e5-8271-0cc57942b86a.jpg)

**Comment by atomrab** [comment]
The door looks great -- I would imagine something very much like this (but without the ring knocker/pull, since we didn't find any of these). For the windows, the traces of iron in the sash blocks suggest hinged shutters like the first image, not grates like the second -- so let's go with the first.

**Comment by ghost** [comment]
I added a simple door for the room 36. But I don't know if you can come into the room. Or maybe that the door should be from one part?

**Comment by atomrab** [comment]
The door looks good, but I see the problem -- one can't get through. We should either make the door have one leaf, or make both leaves open when you push/click on it.

**Comment by ghost** [comment]
I did a research about scripting in Unity. And I added some functionality for our first Door(Alpha version of door animation JavaScript). Now when you are approaching closer to the door, press Key "E" then the doors should slowly open. When they fully opened then you can press Key "E" again and the doors should slowly close.

**Comment by atomrab** [comment]
I see that new doors have started to be added. I don't have my picture with the door swing directions on it, but the door into complex 2 (from alley to room 34) should definitely open in and to the RIGHT, rather than the left, if that hole is really a cesspit -- you'd want to cover it with the door, rather than make it the first thing the visitor sees.

**Comment by ghost** [comment]
As we had discussed last week I added doors based on your plan. Please have a look if now the are open as you like. The only doors not added in on the first floor room 38 and one in the Room 25.

**Comment by atomrab** [comment]
Here's a diagram of where things stand with the 10/15 model and doors and windows. There's a key in the image itself. Also, there is one slight problem with the back door of room 30: with the door the way it is, the doorway is now too narrow for one to go through. I wonder if this door shouldn't open out instead -- I can see that this could have been a problem in real life as well. Or perhaps there wasn't a door here, just a heavy curtain.

![slide1](https://cloud.githubusercontent.com/assets/4740995/19619616/68f6242a-9831-11e6-92d7-b5507d44b0d9.JPG)

**Comment by ghost** [comment]
Can you please check if this issue is resolved, please

**Comment by atomrab** [comment]
Everything is resolved except for the doors on the upper floors above rooms 36 and 38. Those doors should have single leaves, not double (that is, just one panel), and the door to the floor above room 36 is smaller than the doorframe (there's a gap at the top). Everything else is great!

**Comment by atomrab** [comment]
There are also those two additional windows I proposed for room 38 -- if I have to choose between those and the phase 2 modifications, though, we can forget about these.

**Comment by atomrab** [comment]
We're very close to done with this issue, but I'm pretty sure that the upstairs door of room 38 was only one leaf (right now it's two). I have assumed that the interior door to room 36 and the door to the area above that were single leaves as well, but I actually don't know if it's harder to make a door with a single leaf or a door with double leaves, especially under an arch. I assumed that the street-side doors would be double, because it seems like they'd be easier to secure from the inside that way. 

I have a vague preference for single-leaf doors for the interior of complex 3, but if it's a pain to make these (because you haven't made any single-leaf arched doors already), I'm not too attached to it. The only one I really think we need to fix is the upstairs door for room 38, which should definitely be single.

**Comment by atomrab** [comment]
On a related note, I had no idea how many people were trading online in 3D models and textures for 3D models related to medieval doors. Why is there such a big online medieval door model community?

**Comment by atomrab** [comment]
I think we can consider this closed.
