### ISSUE TITLE
Correct interior view of roofs/ceilings

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#24]
Currently the roofs are triangular solids, so the ceilings are flat even when roofs are sloped. The roofs should instead be flat inclined planes on the inside as well. There were probably not any trusses, which you reconstructed in the upper floor of room 38 -- so remove these, and just build the ceilings with beams and rafters.

**Comment by ghost** [comment]
Fix roofs/celling for Room 30, 33, 36, 38. And for all those rooms I put not round  but square beams. Please, let me know should you prefer round like in Room 38 or square one.

**Comment by atomrab** [comment]
We don't have direct evidence for beam shape, but I think it's more likely
that the beams running down the slope were squared, as you've done them
here.

The central beams, though -- the roof-trees, at the apex of the slope of a
gabled roof -- were probably round or rounded. So a combination of square
for the cross-beams and round for the roof-tree in room 38 would probably
be best.

**Comment by atomrab** [comment]
Currently there are beams under the roofs, and beams running up from the walls. We don't need both of these -- just one set of beams is fine (probably the ones under the roofs). But we could re-use the extra set of beams for the lower floors in rooms 38 and 36, which should also be constructed in this manner.

**Comment by Paradoxfx** [comment]
I'm in hangouts

**Comment by atomrab** [comment]
I don't think that the lateral rooms, like 33, had beams running perpendicular to the slope of the roof -- I would guess that they only had the beams that ran in the same direction as the slope (the room is narrower in that dimension, so there's less distance to cover and less strain on the wood).

Also, on the inside, the area over the door is transparent, for some reason:

![image](https://cloud.githubusercontent.com/assets/4740995/13559346/e4077618-e3d8-11e5-9f9a-651d5ea69a14.png)

**Comment by ghost** [comment]
I deleted perpendicular beams. And fixed missing polygons

**Comment by atomrab** [comment]
Beams look good, although at some point it might make sense to make a surface with reeds, like in the house from Lentini, between the beams and the tiles (this would probably have been plastered on the inside). The space over the door looks good and solid now. On the other hand, you can walk through all the walls of room 33 (not true of the other rooms).
