### ISSUE TITLE
Remove shelf/ledge currently at end of courtyard

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#26]
The courtyard should end to the north in a blank wall, midway along room 30 on the other side of the dividing wall. Right now there's a sort of ledge or step (in red, below); this should be pushed back or removed to leave a single flat wall.

![slide1](https://cloud.githubusercontent.com/assets/4740995/13761812/da729458-ea08-11e5-9e30-18b3e09b4078.JPG)

**Comment by ghost** [comment]
Fixed this issue
