### ISSUE TITLE
Closing off the complex 1 side of the model

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#27]
I don't want to keep asking for new components to the model, but I think it would make it look a lot better and more complete if you could add a shell for the long, barn-like building along the west side of the courtyard (that is, complex 1, excavated by Paul Arthur and his team). It doesn't have to have any interior modeling, and it's not even necessary to make it possible to enter the building -- it would just be a dummy, like the shell you built to the north of room 38. I've sketched out a possible solution below -- a flat or arched door, positioned according to the state plan in the folder you have a link to on Box (https://utexas.box.com/s/s0lwh1l1qtmvujh15r3k96fnbk3bpnq6), a flat or arched window in the facade above (both closed with wooden doors/shutters, not openable), and then a gabled roof. 

If you don't have the time to do this, that's ok too -- I just think it would give the model a more finished appearance.

![slide2](https://cloud.githubusercontent.com/assets/4740995/13761959/eecd9cd0-ea09-11e5-9e5b-29dffd687316.JPG)

**Comment by ghost** [comment]
Fixed. I created a house with square door and arched window. Unfortunately, I was not able to open the link (https://utexas.box.com/s/s0lwh1l1qtmvujh15r3k96fnbk3bpnq6). I hope it's what you meant.

**Comment by atomrab** [comment]
This looks fine. I don't think we need to spend more time on it -- if there's time to spare, I'd rather use it for the second phase of complexes 2 and 3. Don't worry about the internal divisions.
