### ISSUE TITLE
Feature: anvil stand and anvil in room 33

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#30]
We know that during the first phase of this room, it served as a blacksmith's smithy, and we're pretty sure that a particular hole in the floor held the stump or log that traditional smiths rest their anvils on. When we're done with the rest of the larger-scale revisions to the model, it would be cool to put in a cylinder to serve as the stump and perhaps just a 2D cutout of an anvil. Or a 3D model from the internet: [http://www.thingiverse.com/thing:31397](http://www.thingiverse.com/thing:31397).

![slide2](https://cloud.githubusercontent.com/assets/4740995/15454506/d074479e-1fff-11e6-90b8-42c0d3f1cd38.JPG)

**Comment by ghost** [comment]
created anvil stand and anvil

**Comment by atomrab** [comment]
Looks good!
