### ISSUE TITLE
Add wooden lintels over all doors without arches

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#31]
All doors that don't have stone arches would have had to have wooden lintels to hold up the masonry above them. We should add visible wooden lintels over all such doors, as here with the door between room 33 and room 28, and the door between 28 and the street:

![slide3](https://cloud.githubusercontent.com/assets/4740995/15454514/3cb3ca1a-2000-11e6-8f04-b74f5d35ef6d.JPG)

and as here with the door of room 30:

![slide11](https://cloud.githubusercontent.com/assets/4740995/15454517/57cf379e-2000-11e6-8ab3-c76d39cf065f.JPG)

And elsewhere as necessary.

**Comment by ghost** [comment]
This issue has been resolved

**Comment by atomrab** [comment]
There are still a few doors that need wooden lintels.

Room 35:

![rm35_lintel](https://cloud.githubusercontent.com/assets/4740995/15801000/cf581ee6-2a4d-11e6-896b-5233739762d2.JPG)

Rooms 29 and 36:

![rm29_36_lintels](https://cloud.githubusercontent.com/assets/4740995/15801003/e0649e94-2a4d-11e6-943d-1802226467a3.JPG)

**Comment by ghost** [comment]
fixed
