### ISSUE TITLE
Raise lintels of specific doors

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#32]
Some of the doors are still a little low. In complex 3, we should raise the lintel (and the wall, to the extent possible, without getting above the roofline of 33) of the door between room 28 and the street:

![slide3](https://cloud.githubusercontent.com/assets/4740995/15454526/922ea44c-2000-11e6-8c80-bc1a6d896354.JPG)

and we should raise the lintel of the door between complex 3 and the courtyard:

![slide8](https://cloud.githubusercontent.com/assets/4740995/15454530/9fb30e96-2000-11e6-835a-7b85981b83d7.JPG)

**Comment by ghost** [comment]
fixed
