### ISSUE TITLE
Add recessed basin in platform under lean-to in room 28

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#33]
The platform of bedrock along the southwest wall of room 28 actually had a basin cut into it, probably to hold water the blacksmith could use to temper iron. Can we add this recess? It can either be oval or square, and should just be a depressed area about 20-25cm deep.

![slide4](https://cloud.githubusercontent.com/assets/4740995/15454598/43b0ef8e-2003-11e6-93bb-d94e0a97b6e0.JPG)

**Comment by ghost** [comment]
added

**Comment by atomrab** [comment]
Looks good!
