### ISSUE TITLE
Fix and improvement to room 29

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#34]
The interior of room 29 has a problematic intersection between two planes, so there's a step up in the floor that isn't present in reality. The floor should be one uniform, flat plane. Also, if we have a chance to add features, there was a pithos in this room more or less where I've put it. It was sitting on the floor, not embedded in it, and was supported by a ring of irregular stones. These pithoi are from a meter to a meter and a half high. I can supply some good photos from the Byzantine catalogue we produced with the Preserve, if necessary.

![slide5](https://cloud.githubusercontent.com/assets/4740995/15454625/06336fb4-2004-11e6-9e02-b96269c70dbd.JPG)

**Comment by ghost** [comment]
Added pithoi, but not stones

**Comment by atomrab** [comment]
The pithos looks good, but the floor level still needs to be fixed.

**Comment by atomrab** [comment]
Actually, there were two pithoi in this room. In the picture below, you've already added the one where the green circle is; the other one was where the red circle is, in the west corner of the room. The door is on the right of the picture. You could just copy the one that's in there and put the copy in the corner. 

![rm29_pithoi](https://cloud.githubusercontent.com/assets/4740995/15801067/b16a2c10-2a4f-11e6-9137-4a9c794649c6.JPG)

**Comment by ghost** [comment]
fixed
