### ISSUE TITLE
Add tile roof and additional support post to balcony in complex 3

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#36]
It's likely, from the photos that I looked at of Turkish vernacular architecture, that this balcony also had a tiled roof. If that's the case, it should have a fourth support post running up from the top of the wall of room 29 to the north edge of its roof.

![slide7](https://cloud.githubusercontent.com/assets/4740995/15454647/a68d1942-2004-11e6-9250-a1e4ac35a3a0.JPG)

**Comment by ghost** [comment]
fixed
