### ISSUE TITLE
Add wall and lintel over door between rooms 34 and 25

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#37]
The opening between these two rooms had a door (the lock was found), which suggests that it would have had a proper door frame, including a stretch of wall above a wooden lintel. Let's add these.

![slide9](https://cloud.githubusercontent.com/assets/4740995/15454728/7524f378-2006-11e6-9ed3-054319a8f702.JPG)

**Comment by ghost** [comment]
fixed
