### ISSUE TITLE
Add pithoi in room 35

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#38]
We know that there were two pithoi in room 35 at the time of its destruction. The bedrock platform on the east side of the room had two shallow circular depressions cut into it; these were probably meant to hold the bases of two smallish pithoi. If we get to the stage of adding features, it would be nice to include these.

![slide10](https://cloud.githubusercontent.com/assets/4740995/15454741/b5d7e240-2006-11e6-8ef6-b05daf1c14c0.JPG)

**Comment by ghost** [comment]
added pithoi
