### ISSUE TITLE
Remove room 31a, behind room 30, in phase 1 and raise courtyard to same level outside room 30

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#4]
Room 31a, behind room 30, didn't exist in the first phase. The level of the courtyard, which currently dips down to the level of room 30, should be as high as it is elsewhere right up to the walls of room 30 (when room 31a is added in the second phase, its floor continues to be higher than room 30's).

![slide4](https://cloud.githubusercontent.com/assets/4740995/9562060/93ffc2b2-4e26-11e5-9929-ee37dc56c1a3.JPG)

**Comment by ghost** [comment]
Delete room 31A on phase 1.

**Comment by ghost** [comment]
Fix the courtyard level.

**Comment by ghost** [comment]
But I'm not sure about level for the room 31A? Adam can you please have a look on it?

**Comment by atomrab** [comment]
The floor level for 31a should be at the same level as that of the rest of
the courtyard (room 31) behind room 30 (not the same level as room 30).
Send me a new Unity file when you're ready and I'll take a look!

**Comment by ghost** [comment]
Fix the issue.
