### ISSUE TITLE
Chapel: raise roof and walls

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#40]
I think the chapel was probably a bit taller than we've made it here -- the walls were probably at least as tall as the SW wall of room 28. The roof and the apse should be raised accordingly (the top of the apse half-dome should not be more than 50-75cm below the peak of the gabled roof of the rest of the chapel).

![slide13](https://cloud.githubusercontent.com/assets/4740995/15454760/2c021882-2007-11e6-9161-8c4b939cdf71.JPG)

**Comment by ghost** [comment]
fixed

**Comment by atomrab** [comment]
We're close, but the apse is either too tall or the building is still too short. The top half-dome of the apse should be significantly lower than the line of the roof of the rectangular part of the building -- I take it back, 50-75cm might be too little. Maybe a meter? See the image I linked to for #51.

**Comment by ghost** [comment]
fixed
