### ISSUE TITLE
Door to chapel needs a wooden lintel

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#41]
As for the other doors without arches in the complex, this door needs a wooden lintel. When the roof and walls are raised, this door should not increase much in height -- there should be more wall above it.

![slide14](https://cloud.githubusercontent.com/assets/4740995/15454769/50483ed8-2007-11e6-95e4-6acc5e423ba7.JPG)

**Comment by ghost** [comment]
fixed
