### ISSUE TITLE
Chapel: underside of roof should be visible, not ceiling

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#42]
The chapel still has a flat ceiling, but like the other structures (eg room 33), when you look up you should see the underside of the gabled, tiled roof -- that is, you're looking up at a triangular space, not a flat one.

![slide15](https://cloud.githubusercontent.com/assets/4740995/15454788/9dd11b5c-2007-11e6-8adb-bb79f016c178.JPG)

**Comment by atomrab** [comment]
This looks a lot better, but there is still an extra triangular projection between the pitched roof and the apse. The apse wall should be a single plane from the roof to the floor, and the pitched roof should end right at that wall. Maybe that solid could just be pushed back to the line of the exterior wall on the apse side?

**Comment by ghost** [comment]
fixed
