### ISSUE TITLE
Chapel: add graves, with covers that open

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#44]
It would be fun to add the graves in the chapel -- their length and width are on the plan, and they were both about 1 meter deep. If we do add them, by creating empty spaces in those areas, we should also add wooden covers, like horizontal doors, that could be opened toward the viewer to reveal a photograph of the depositions (could we size one of these photos to match the size of the floor of one of the graves, and use it as a texture?).

![slide17](https://cloud.githubusercontent.com/assets/4740995/15454817/54c1163c-2008-11e6-9391-9238d1fe3b59.JPG)

**Comment by ghost** [comment]
Done, I did put a transparent plane for the graves for a time.

**Comment by atomrab** [comment]
This looks awesome -- I like the way you've done this. But we need different images for the bottom of each grave. I have uploaded images for each of these to the main area of this repo. The one with the filename that begins "CH02" should go in the grave to the north (the one closer to the viewer in the image above, and farther from the door); the other one, with the filename beginning "PH", should go in the grave to the south, closer to the door. In both graves, the heads should be toward the back wall of the church and the feet toward the apse.

**Comment by ghost** [comment]
fixed
