### ISSUE TITLE
Walls that surround the courtyard and open spaces need caps

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#45]
The walls that divide the courtyard from complex 3, or divide parts of complex 3 from each other, but are not covered by roofs should have some kind of cap -- the easiest type to use would be a single row of tiles pitched in the direction of the courtyard, or a double-row of tiles pitched to either side of the wall. I have also seen half-round caps, but since these buildings don't use lime mortar, tiles are probably the better bet. If these walls weren't capped, a lot of water would have been able to get into them, and they would have been very hard to maintain. I've shown two here as an example, but basically any wall that isn't already covered by a roof should have its own little roof.

![slide18](https://cloud.githubusercontent.com/assets/4740995/15454829/c586c286-2008-11e6-8a76-1843b615ad84.JPG)

**Comment by ghost** [comment]
Fixed for all the Courtyard walls

**Comment by atomrab** [comment]
Almost there. Two final modifications: we should do this on the lintel over the doorway between rooms 34 and 25; and the wall along the far side of the courtyard doesn't need a cap, because it's actually the wall of a building, which I hope you'll be able to frame (see #27).

**Comment by ghost** [comment]
fixed
