### ISSUE TITLE
Add stone base for wooden support at courtyard end of balcony in room 32

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#47]
The angled support for the balcony stood on a stone in the courtyard, which you can see in the photo below. If possible, add this flat stone as a base for that support in the model.

![rm32_balcony_support_stone](https://cloud.githubusercontent.com/assets/4740995/15801124/fb9ddb3c-2a50-11e6-8ef4-b4e500138e75.JPG)

![phch04sr0342](https://cloud.githubusercontent.com/assets/4740995/15801121/e4cd393e-2a50-11e6-9729-392f10d15ee9.jpg)

**Comment by ghost** [comment]
Issue fixed
