### ISSUE TITLE
Move left window in facade of room 38 to be more symmetrical with extended upper floor

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#5]
We talked about this, too -- they just seem too close together now that we've extended that floor.

![slide5](https://cloud.githubusercontent.com/assets/4740995/9562073/c471e574-4e26-11e5-879b-71301546d6de.JPG)

**Comment by ghost** [comment]
Fix this issue. And I added more space inside the first room form this extension.

**Comment by atomrab** [comment]
Corrected, but there's a projection of the ceiling inside the room on the extended side that should be removed. Also, I suspect that there was no flat ceiling with an attic below the roof -- so remove that, inside just have the bare beams supporting the roof.

**Comment by atomrab** [comment]
I think we're on the same page now about this -- I'll wait to see what it looks like next week. Thanks!

**Comment by atomrab** [comment]
The roof is fine now, but I think that extra block along the wall over the extension is still there. I'll check with the next iteration.

**Comment by ghost** [comment]
Fixed the issue with extra block along the wall
