### ISSUE TITLE
Distortion in image in chapel info window

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#50]
Something has happened to the aspect ratio of this image; it should be rectangular. I would also tend to put the window on the opposite (courtyard) side of the church, closer to where the remains depicted were found. It makes more sense to the viewer if the photo is oriented or at least placed in the model near where it was taken in reality.

![image](https://cloud.githubusercontent.com/assets/4740995/16172977/8be3d6c0-3559-11e6-8045-8e2ba2559028.png)

**Comment by ghost** [comment]
fixed

**Comment by atomrab** [comment]
Keep on outside of chapel, but on external courtyard side (now it's inside); correct image (should be rectangular, not square).

**Comment by ghost** [comment]
fixed
