### ISSUE TITLE
Chapel also needs a tile roof

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#51]
This probably goes without saying, but the chapel and the apse also need tile roofs.

![image](https://cloud.githubusercontent.com/assets/4740995/16172990/ea5529fc-3559-11e6-8635-a9592541a4ff.png)

**Comment by ghost** [comment]
fixed

**Comment by atomrab** [comment]
The apse still needs tiles -- you could use this Byzantine chapel as a model (also for the proportional height of apse vs. roof): http://cache4.asset-cache.net/gc/577714037-apse-of-the-byzantine-church-of-michael-gettyimages.jpg?v=1&c=IWSAsset&k=2&d=9QMziWNtBI6whP66vhs4oV3vmt3TnKLsl589YhNimlsbzn2AwM96pk6jvcIobAtTZG7FexSxD4yqe3CRGqEKMwsHmwpxmEIRdDfYSr9FfDY%3D

**Comment by ghost** [comment]
fixed

**Comment by ghost** [comment]
The only thing is that now when I added a tiled roof, it goes in to the wall. But I used a top plan for the chapel.

**Comment by atomrab** [comment]
Yeah, I don't know how this would have looked -- the apse wall definitely runs into the wall of room 28. Either the wall between the two was a lot lower, so that the tiles came over the top -- which would be strange, since then you'd be able to look over it from the courtyard, and there would be two different heights (for the door to the court) -- or it looked more or less like you've made it. I think it's probably the latter, so this is good.
