### ISSUE TITLE
Info window for room 30 should be on the other side of this wall, inside the room

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#53]
This info window would be more understandable if it too were inside the room it describes, probably on the other side of this particular wall, opposite the door to room 24 (that way, it will be viewed from the same perspective as the photo was taken).

![image](https://cloud.githubusercontent.com/assets/4740995/16173030/ec2ecf0c-355a-11e6-8435-3c62e07fbf87.png)

**Comment by ghost** [comment]
I moved it inside. But I can't find where is Room 24 on the plan?

**Comment by atomrab** [comment]
Sorry, I meant the door to room 25 (the corridor right in front of room 30 on the other side).

**Comment by ghost** [comment]
Fixed

**Comment by atomrab** [comment]
Move this info window to the opposite wall -- when you come into the room from the door of the corridor, you should be looking at it, a little to the right of your line of sight.

**Comment by ghost** [comment]
fixed
