### ISSUE TITLE
Trim tile roof over room 29 (or raise courtyard wall a little)

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#55]
This roof extends too far over the adjoining wall of the courtyard, and sort of merges into it. In reality, it's more likely that the slope of the roof would have started at or below the top of the wall, so that water from the roof didn't run off into the wall itself. If you think you'll have time to add half-round or tile caps to these walls (again, to prevent water from running into the walls and causing them to collapse), that might take care of the problem.

![image](https://cloud.githubusercontent.com/assets/4740995/17833174/253b6f9c-66db-11e6-82d8-830fc979d643.png)

**Comment by ghost** [comment]
Fixed
