### ISSUE TITLE
Add cover (half-round) tiles to ridgelines of pitched roofs

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#56]
The pitched roofs over complex 2 and the chapel have gaps at the ridge-line (if you stand in the room and look up, you can see sky). 

![image](https://cloud.githubusercontent.com/assets/4740995/17833179/6ec75662-66db-11e6-82b1-bae3707f8e32.png)

In reality, these would have been covered by tiles to prevent water from getting in (a single line of rounded cover-tiles):

![image](https://cloud.githubusercontent.com/assets/4740995/17833188/b227db5c-66db-11e6-9523-3e7ddc043d4d.png)

**Comment by ghost** [comment]
Fixed on two roofs
