### ISSUE TITLE
Make roof of room 33 watertight

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#57]
Can this roof be extended a little more toward the wall of room 36, without too much trouble? There's currently a gap. But if it's a pain, especially with the texturing, don't worry about it -- it's not critical.

![image](https://cloud.githubusercontent.com/assets/4740995/17833200/08807374-66dc-11e6-8037-f4a9a7bdc0f1.png)

**Comment by ghost** [comment]
fixed. (It was happened because walls are not parallel on the plan)

**Comment by atomrab** [comment]
Yeah, they are totally not parallel in reality either. I often wonder how they managed to keep these houses up for the 75 or 100 years that they were occupied!
