### ISSUE TITLE
Room 30 should have a pitched roof sloping down toward the corridor

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#6]
Room 30 definitely had a pitched roof, because it was tiled, and the likely direction of the slope is into the corridor between complex 2 and complex 3.

![slide6](https://cloud.githubusercontent.com/assets/4740995/9562079/f8a2e6fe-4e26-11e5-8f64-5dcb7aef7050.JPG)

**Comment by ghost** [comment]
Fix this issue. And I added the actual roof with tiles

**Comment by ghost** [comment]
Rotate the roof as it should be
