### ISSUE TITLE
Finish area NW of courtyard 31

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#62]
Right now this is a featureless block, which looks a little weird. The side next to room 31 should be a plastered wall, probably with the same tile covering on top of it (in phase 2, it will become one of the walls of room 31a). The ground level on that side is around the level of the courtyard on the other side of the wall in that area. The area was occupied by a beaten-earth surface with a big hole cut into it and filled with trash, so we assume it was an open area -- we could just line up the surface with the courtyard and the surface next to the Complex 1 building, and give it the same texture as those. 

![courtyard_terracewall](https://cloud.githubusercontent.com/assets/4740995/21936789/1670acb0-d978-11e6-8895-2f51b5a0f758.PNG)

![phch04sr0359](https://cloud.githubusercontent.com/assets/4740995/21936812/2ebcbaac-d978-11e6-990f-8a48115afb79.jpg)

**Comment by ghost** [comment]
Just fix it. Please have a look if it's what you need

**Comment by atomrab** [comment]
Almost perfect, but there's an extra wall for some reason. The dividing wall should just be an extension of the W wall of room 30 (see below: the yellow highlighting is where the wall should be; I've dashed in red the current incorrect position of that wall). Sorry I didn't catch this earlier!

![rear_court](https://cloud.githubusercontent.com/assets/4740995/26027821/97c6ffe2-37da-11e7-8414-f2c173a3b3c6.JPG)
