### ISSUE TITLE
Door between rooms 32 and 36 should have an arched lintel

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#63]
There was a burned wooden plan with a curved end in room 36, probably from this door, which suggests the door had an arched lintel rather than a flat one. Sorry, I should have caught this sooner.

![rm32_36_groundfloor_arch_draw](https://cloud.githubusercontent.com/assets/4740995/21950742/8ee925a0-d9c3-11e6-917d-46e868ad6e02.PNG)

**Comment by ghost** [comment]
fixed the issue
