### ISSUE TITLE
Floor of room 30 should be raised ca. 10cm, doors on either side should have stone sills

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#7]
I know that I passed on Z coordinates for this floor, but the model looks a lot lower than the original, and I may have been too conservative on coordinates. If possible, raise the floor about 10cm. Each door should also have a stone sill in the form of a rectangular solid (these are visible in the photos I sent). 

![slide7](https://cloud.githubusercontent.com/assets/4740995/9562093/453f547a-4e27-11e5-9fda-e7d8aada4345.JPG)

**Comment by ghost** [comment]
Fix this issue. The only thing is that I'm not sure if the stone sills are not to high

**Comment by atomrab** [comment]
I think that the sills are ok -- the main issue is sizing the first-person body so that the user can step up over those sills without having to jump. Is that possible?
