### ISSUE TITLE
Add a "building" north of complex 2, just to block off the street and court

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#9]
We know that there were walls that extended north along the lines of the long walls of room 38. We don't have any other information about that building, but in order to model the streetscape, we should wall off that area north of room 38 on both the street and the courtyard side. You could add a simple pitched roof (probably sloped toward the street) so that a user who is flying won't see an empty shell.

![slide9](https://cloud.githubusercontent.com/assets/4740995/9562111/c0199fac-4e27-11e5-9c18-a85412902446.JPG)

**Comment by ghost** [comment]
I added additional building. And make a slope down to street with roof tiles

**Comment by atomrab** [comment]
Please extend this to the edge of the terrain, so the user can't walk around it. Otherwise, looks great!

**Comment by ghost** [comment]
Fixed this issue
